services:
  - type: web
    name: pinterest-scraper-api
    env: python
    plan: free
    buildCommand: ""
    startCommand: uvicorn api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
